version: '3.8'
services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - mongo
      - postgres
    # Ejecuta gunicorn para producción
    command: gunicorn -w 4 -b 0.0.0.0:5000 "app:create_app()"
    # Puedes eliminar FLASK_ENV o ponerlo en production si aún lo necesitás
    environment:
      FLASK_ENV: production
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  mongo:
    image: mongo:5
    container_name: flask_api_mongo
#    ports:
 #     - "27017:27017"

  postgres:
    image: postgres:14-bullseye
    container_name: postgresql-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
   # ports:
    #  - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  pgdata:
